# Generated by Django 4.2.2 on 2023-06-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_object_alter_article_options_relationship_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationship',
            options={'verbose_name': 'Тематики статьи', 'verbose_name_plural': 'Тематики статей'},
        ),
    ]
