# Generated by Django 4.2.2 on 2023-06-16 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_relationship_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='invite_reason',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='inviter',
        ),
        migrations.AddField(
            model_name='relationship',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationship',
            name='object_main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='articles.object'),
        ),
    ]
