# Generated by Django 4.2.2 on 2023-06-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_relationship_invite_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='delete',
        ),
        migrations.AlterField(
            model_name='relationship',
            name='object_main',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
