# Generated by Django 4.2.2 on 2023-06-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_object_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='relationships',
            field=models.ManyToManyField(related_name='related_objects', through='articles.Relationship', to='articles.article', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='object',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
