# Generated by Django 4.2.2 on 2023-06-16 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_object_relationships_alter_object_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='relationships',
            field=models.ManyToManyField(related_name='related_objects', through='articles.Relationship', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='articles.article', verbose_name='Раздел'),
        ),
    ]
