# Generated by Django 4.2.2 on 2023-06-16 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_object_options_alter_relationship_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='relationships',
        ),
        migrations.AddField(
            model_name='article',
            name='relationships',
            field=models.ManyToManyField(related_name='related_objects', through='articles.Relationship', to='articles.object'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='articles.article', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='articles.object', verbose_name='Тег'),
        ),
    ]
