# Generated by Django 4.2.2 on 2023-06-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_remove_object_relationships_article_relationships_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='relationships',
        ),
        migrations.AddField(
            model_name='object',
            name='relationships',
            field=models.ManyToManyField(related_name='related_objects', through='articles.Relationship', to='articles.article'),
        ),
    ]
