# Generated by Django 4.2.2 on 2023-06-16 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_relationship_article_alter_relationship_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='object_main',
        ),
    ]
