# Generated by Django 4.2.2 on 2023-06-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_relationship_object_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='relationships',
        ),
        migrations.AddField(
            model_name='object',
            name='scopes',
            field=models.ManyToManyField(related_name='scope', through='articles.Relationship', to='articles.article'),
        ),
    ]
