# Generated by Django 4.2.2 on 2023-06-16 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_alter_relationship_article_alter_relationship_tag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together=set(),
        ),
    ]
